// Client-side PDF generation using jspdf + jspdf-autotable
import { NewtonIteration, NewtonResult } from "@/lib/newton";

function formatNum(n: number): string {
  if (!isFinite(n)) return String(n);
  if (Math.abs(n) < 1e-4 && n !== 0) return n.toExponential(6);
  return n.toPrecision(8);
}

export async function downloadPDF(
  result: NewtonResult,
  func: string,
  x0: number,
  tolerance: number,
  maxIter: number
) {
  // Dynamic import for client-side only
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  const accentRGB: [number, number, number] = [232, 93, 58];
  const inkRGB: [number, number, number] = [10, 10, 15];
  const muteRGB: [number, number, number] = [138, 136, 128];
  const blueRGB: [number, number, number] = [58, 123, 213];

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // ---- Header ----
  doc.setFillColor(...accentRGB);
  doc.rect(0, 0, pageW, 22, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("NewtonSolve", 14, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Newton's Method — Numerical Analysis Report", pageW / 2, 14, { align: "center" });
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageW - 14, 14, { align: "right" });

  // ---- Parameters ----
  let y = 30;
  doc.setTextColor(...inkRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Input Parameters", 14, y);

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...muteRGB);

  const params = [
    ["Function f(x)", `f(x) = ${func}`],
    ["Initial Guess x₀", String(x0)],
    ["Tolerance ε", String(tolerance)],
    ["Max Iterations", String(maxIter)],
  ];
  params.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...muteRGB);
    doc.text(`${label}:`, 14, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...inkRGB);
    doc.text(value, 60, y);
    y += 5;
  });

  // ---- Result ----
  y += 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...inkRGB);
  doc.text("Result", 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  const statusColor: [number, number, number] = result.converged
    ? [22, 163, 74]
    : result.diverged
    ? [220, 38, 38]
    : [234, 179, 8];

  doc.setTextColor(...statusColor);
  doc.text(result.message, 14, y);
  y += 5;

  if (result.root !== null) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...blueRGB);
    doc.text(`Root ≈ ${result.root.toPrecision(12)}`, 14, y);
    y += 5;
  }

  // ---- Formula box ----
  y += 2;
  doc.setFillColor(245, 243, 238);
  doc.roundedRect(14, y, pageW - 28, 10, 2, 2, "F");
  doc.setTextColor(...muteRGB);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.text("Newton's Method Formula:  x_{n+1} = x_n - f(x_n) / f'(x_n)", pageW / 2, y + 6.5, { align: "center" });
  y += 16;

  // ---- Table ----
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...inkRGB);
  doc.text("Iteration Table", 14, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [["n", "xₙ", "f(xₙ)", "f′(xₙ)", "xₙ₊₁", "|error|"]],
    body: result.iterations.map((it: NewtonIteration) => [
      String(it.n),
      formatNum(it.x_n),
      formatNum(it.f_x_n),
      formatNum(it.f_prime_x_n),
      formatNum(it.x_next),
      it.error.toExponential(4),
    ]),
    styles: { fontSize: 8, font: "courier", cellPadding: 3 },
    headStyles: {
      fillColor: inkRGB,
      textColor: [245, 243, 238],
      fontSize: 8.5,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [250, 249, 246] },
    rowPageBreak: "auto",
  });

  // ---- Footer ----
  const totalPages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(...muteRGB);
    doc.text(`Generated by NewtonSolve  |  Page ${i} of ${totalPages}`, pageW / 2, pageH - 6, { align: "center" });
  }

  doc.save(`newton-method-${func.replace(/[^a-z0-9]/gi, "_").slice(0, 20)}.pdf`);
}
